name: Build Everytone Tuner

on: [push, pull_request]

env: {}

jobs:
  build-linux:
    name: Build Everytone Tuner (Linux)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install zip unzip libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev  libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
      - name: Setup JUCE
        run: |
          echo finding latest JUCE release
          DOWNLOAD_URL=$( \
            curl -s https://api.github.com/repos/juce-framework/juce/releases/latest \
            | grep "browser_download_url.*linux" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            )
          echo downloading $DOWNLOAD_URL
          wget $DOWNLOAD_URL -O juce.zip &>/dev/null
          unzip -d ~ juce.zip &>/dev/null
      - name: Build Everytone Tuner
        run: |
          ~/JUCE/Projucer --resave everytone-tuner.jucer
          cd Builds/LinuxMakefile
          make CONFIG=Release
      - name: Zip binaries
        run: |
          cd Builds/LinuxMakefile/build
          ls -i
          zip -q everytone-tuner_linux.zip Everytone\ Tuner Everytone\ Tuner.a Everytone\ Tuner.vst3
      - name: Upload Everytone Tuner
        uses: actions/upload-artifact@v2
        with:
          name: everytone-tuner_linux
          path: Builds/LinuxMakefile/build/everytone-tuner_linux.zip
          if-no-files-found: error
          

